apiVersion: v1
kind: Service
metadata:
  name: posts-svc
spec:
  type: NodePort
  selector:
    app: posts # label to find PODS
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # port to expose outside, could be different to targetPort
      targetPort: 4000 #usrv post service (same of posts/index.js)
